services:
  - type: web
    name: slobos-afk-aternos-botchotta
    runtime: node
    buildCommand: npm install --no-audit --no-fund --fetch-retries=5 --fetch-retry-factor=2 --fetch-retry-mintimeout=1000 --fetch-retry-maxtimeout=60000
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22.22.0"
